<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('cities')->insert([
            //서울특별시
            ['state_id'=>1, 'city_name'=>'강남구'],
            ['state_id'=>1, 'city_name'=>'강동구'],
            ['state_id'=>1, 'city_name'=>'강북구'],
            ['state_id'=>1, 'city_name'=>'강서구'],
            ['state_id'=>1, 'city_name'=>'관악구'],
            ['state_id'=>1, 'city_name'=>'광진구'],
            ['state_id'=>1, 'city_name'=>'구로구'],
            ['state_id'=>1, 'city_name'=>'금천구'],
            ['state_id'=>1, 'city_name'=>'노원구'],
            ['state_id'=>1, 'city_name'=>'도봉구'],
            ['state_id'=>1, 'city_name'=>'동대문구'],
            ['state_id'=>1, 'city_name'=>'동작구'],
            ['state_id'=>1, 'city_name'=>'마포구'],
            ['state_id'=>1, 'city_name'=>'서대문구'],
            ['state_id'=>1, 'city_name'=>'서초구'],
            ['state_id'=>1, 'city_name'=>'성동구'],
            ['state_id'=>1, 'city_name'=>'성북구'],
            ['state_id'=>1, 'city_name'=>'송파구'],
            ['state_id'=>1, 'city_name'=>'양천구'],
            ['state_id'=>1, 'city_name'=>'영등포구'],
            ['state_id'=>1, 'city_name'=>'용산구'],
            ['state_id'=>1, 'city_name'=>'은평구'],
            ['state_id'=>1, 'city_name'=>'종로구'],
            ['state_id'=>1, 'city_name'=>'중구'],
            ['state_id'=>1, 'city_name'=>'중랑구'],
            //강원도
            ['state_id'=>2, 'city_name'=>'강릉시'],
            ['state_id'=>2, 'city_name'=>'고성군'],
            ['state_id'=>2, 'city_name'=>'동해시'],
            ['state_id'=>2, 'city_name'=>'삼척시'],
            ['state_id'=>2, 'city_name'=>'속초시'],
            ['state_id'=>2, 'city_name'=>'양구군'],
            ['state_id'=>2, 'city_name'=>'양양군'],
            ['state_id'=>2, 'city_name'=>'영월군'],
            ['state_id'=>2, 'city_name'=>'원주시'],
            ['state_id'=>2, 'city_name'=>'인제군'],
            ['state_id'=>2, 'city_name'=>'정선군'],
            ['state_id'=>2, 'city_name'=>'철원군'],
            ['state_id'=>2, 'city_name'=>'춘천시'],
            ['state_id'=>2, 'city_name'=>'태백시'],
            ['state_id'=>2, 'city_name'=>'평창군'],
            ['state_id'=>2, 'city_name'=>'흥천군'],
            ['state_id'=>2, 'city_name'=>'화천군'],
            ['state_id'=>2, 'city_name'=>'횡성군'],
            //충청남도
            ['state_id'=>3, 'city_name'=>'계룡시'],
            ['state_id'=>3, 'city_name'=>'공주시'],
            ['state_id'=>3, 'city_name'=>'금산군'],
            ['state_id'=>3, 'city_name'=>'논산시'],
            ['state_id'=>3, 'city_name'=>'당진시'],
            ['state_id'=>3, 'city_name'=>'보령시'],
            ['state_id'=>3, 'city_name'=>'부여군'],
            ['state_id'=>3, 'city_name'=>'서산시'],
            ['state_id'=>3, 'city_name'=>'서천군'],
            ['state_id'=>3, 'city_name'=>'아산시'],
            ['state_id'=>3, 'city_name'=>'예산군'],
            ['state_id'=>3, 'city_name'=>'천안시'],
            ['state_id'=>3, 'city_name'=>'청양군'],
            ['state_id'=>3, 'city_name'=>'태안군'],
            ['state_id'=>3, 'city_name'=>'홍성군'],
            //충청북도
            ['state_id'=>4, 'city_name'=>'괴산군'],
            ['state_id'=>4, 'city_name'=>'단양군'],
            ['state_id'=>4, 'city_name'=>'보은군'],
            ['state_id'=>4, 'city_name'=>'영동군'],
            ['state_id'=>4, 'city_name'=>'옥천군'],
            ['state_id'=>4, 'city_name'=>'음성군'],
            ['state_id'=>4, 'city_name'=>'제천시'],
            ['state_id'=>4, 'city_name'=>'증평군'],
            ['state_id'=>4, 'city_name'=>'진천군'],
            ['state_id'=>4, 'city_name'=>'청원군'],
            ['state_id'=>4, 'city_name'=>'청주시'],
            ['state_id'=>4, 'city_name'=>'충주시'],
            //전라남도
            ['state_id'=>5, 'city_name'=>'강진군'],
            ['state_id'=>5, 'city_name'=>'고흥군'],
            ['state_id'=>5, 'city_name'=>'곡성군'],
            ['state_id'=>5, 'city_name'=>'광양시'],
            ['state_id'=>5, 'city_name'=>'구례군'],
            ['state_id'=>5, 'city_name'=>'나주시'],
            ['state_id'=>5, 'city_name'=>'담양군'],
            ['state_id'=>5, 'city_name'=>'목포시'],
            ['state_id'=>5, 'city_name'=>'무안군'],
            ['state_id'=>5, 'city_name'=>'보성군'],
            ['state_id'=>5, 'city_name'=>'순천시'],
            ['state_id'=>5, 'city_name'=>'신안군'],
            ['state_id'=>5, 'city_name'=>'여수시'],
            ['state_id'=>5, 'city_name'=>'영광군'],
            ['state_id'=>5, 'city_name'=>'영암군'],
            ['state_id'=>5, 'city_name'=>'완도군'],
            ['state_id'=>5, 'city_name'=>'장성군'],
            ['state_id'=>5, 'city_name'=>'장흥군'],
            ['state_id'=>5, 'city_name'=>'진도군'],
            ['state_id'=>5, 'city_name'=>'함평군'],
            ['state_id'=>5, 'city_name'=>'해남군'],
            ['state_id'=>5, 'city_name'=>'화순군'],
            //전라북도
            ['state_id'=>6, 'city_name'=>'고창군'],
            ['state_id'=>6, 'city_name'=>'군산시'],
            ['state_id'=>6, 'city_name'=>'김제시'],
            ['state_id'=>6, 'city_name'=>'남원시'],
            ['state_id'=>6, 'city_name'=>'무주군'],
            ['state_id'=>6, 'city_name'=>'부안군'],
            ['state_id'=>6, 'city_name'=>'순창군'],
            ['state_id'=>6, 'city_name'=>'완주군'],
            ['state_id'=>6, 'city_name'=>'익산시'],
            ['state_id'=>6, 'city_name'=>'임실군'],
            ['state_id'=>6, 'city_name'=>'장수군'],
            ['state_id'=>6, 'city_name'=>'전주시'],
            ['state_id'=>6, 'city_name'=>'정읍시'],
            ['state_id'=>6, 'city_name'=>'진안군'],
            //대구광역시
            ['state_id'=>7, 'city_name'=>'시남구'],
            ['state_id'=>7, 'city_name'=>'달서구'],
            ['state_id'=>7, 'city_name'=>'달성군'],
            ['state_id'=>7, 'city_name'=>'동구'],
            ['state_id'=>7, 'city_name'=>'북구'],
            ['state_id'=>7, 'city_name'=>'서구'],
            ['state_id'=>7, 'city_name'=>'수성구'],
            ['state_id'=>7, 'city_name'=>'중구'],
            //대전광역시
            ['state_id'=>8, 'city_name'=>'대덕구'],
            ['state_id'=>8, 'city_name'=>'동구'],
            ['state_id'=>8, 'city_name'=>'서구'],
            ['state_id'=>8, 'city_name'=>'유성구'],
            ['state_id'=>8, 'city_name'=>'중구'],
            //부산광역시
            ['state_id'=>9, 'city_name'=>'강서구'],
            ['state_id'=>9, 'city_name'=>'금정구'],
            ['state_id'=>9, 'city_name'=>'기장군'],
            ['state_id'=>9, 'city_name'=>'남구'],
            ['state_id'=>9, 'city_name'=>'동구'],
            ['state_id'=>9, 'city_name'=>'동래구'],
            ['state_id'=>9, 'city_name'=>'부산진구'],
            ['state_id'=>9, 'city_name'=>'북구'],
            ['state_id'=>9, 'city_name'=>'사상구'],
            ['state_id'=>9, 'city_name'=>'사하구'],
            ['state_id'=>9, 'city_name'=>'서구'],
            ['state_id'=>9, 'city_name'=>'수영구'],
            ['state_id'=>9, 'city_name'=>'연제구'],
            ['state_id'=>9, 'city_name'=>'영도구'],
            ['state_id'=>9, 'city_name'=>'중구'],
            ['state_id'=>9, 'city_name'=>'해운대구'],
            //울산광역시
            ['state_id'=>10 , 'city_name'=>'남구'],
            ['state_id'=>10 , 'city_name'=>'동구'],
            ['state_id'=>10 , 'city_name'=>'북구'],
            ['state_id'=>10 , 'city_name'=>'울주군'],
            ['state_id'=>10 , 'city_name'=>'중구'],
            //인천광역시
            ['state_id'=>11, 'city_name'=>'강화군'],
            ['state_id'=>11, 'city_name'=>'계양구'],
            ['state_id'=>11, 'city_name'=>'남구'],
            ['state_id'=>11, 'city_name'=>'남동구'],
            ['state_id'=>11, 'city_name'=>'동구'],
            ['state_id'=>11, 'city_name'=>'부평구'],
            ['state_id'=>11, 'city_name'=>'서구'],
            ['state_id'=>11, 'city_name'=>'연수구'],
            ['state_id'=>11, 'city_name'=>'옹진군'],
            ['state_id'=>11, 'city_name'=>'중구'],
            //광주광역시
            ['state_id'=>12, 'city_name'=>'광산구'],
            ['state_id'=>12, 'city_name'=>'남구'],
            ['state_id'=>12, 'city_name'=>'동구'],
            ['state_id'=>12, 'city_name'=>'북구'],
            ['state_id'=>12, 'city_name'=>'서구'],
            //경기도
            ['state_id'=>13, 'city_name'=>'가평군'],
            ['state_id'=>13, 'city_name'=>'고양시'],
            ['state_id'=>13, 'city_name'=>'과천시'],
            ['state_id'=>13, 'city_name'=>'광명시'],
            ['state_id'=>13, 'city_name'=>'광주시'],
            ['state_id'=>13, 'city_name'=>'구리시'],
            ['state_id'=>13, 'city_name'=>'군포시'],
            ['state_id'=>13, 'city_name'=>'김포시'],
            ['state_id'=>13, 'city_name'=>'남양주시'],
            ['state_id'=>13, 'city_name'=>'동두천시'],
            ['state_id'=>13, 'city_name'=>'부천시'],
            ['state_id'=>13, 'city_name'=>'성남시'],
            ['state_id'=>13, 'city_name'=>'수원시'],
            ['state_id'=>13, 'city_name'=>'시흥시'],
            ['state_id'=>13, 'city_name'=>'안산시'],
            ['state_id'=>13, 'city_name'=>'안성시'],
            ['state_id'=>13, 'city_name'=>'안양시'],
            ['state_id'=>13, 'city_name'=>'양주시'],
            ['state_id'=>13, 'city_name'=>'여주시'],
            ['state_id'=>13, 'city_name'=>'오산시'],
            ['state_id'=>13, 'city_name'=>'용인시'],
            ['state_id'=>13, 'city_name'=>'의왕시'],
            ['state_id'=>13, 'city_name'=>'의정부시'],
            ['state_id'=>13, 'city_name'=>'이천시'],
            ['state_id'=>13, 'city_name'=>'파주시'],
            ['state_id'=>13, 'city_name'=>'평택시'],
            ['state_id'=>13, 'city_name'=>'포천시'],
            ['state_id'=>13, 'city_name'=>'하남시'],
            ['state_id'=>13, 'city_name'=>'화성시'],
            //경상남도
            ['state_id'=>14, 'city_name'=>'거제시'],
            ['state_id'=>14, 'city_name'=>'거창군'],
            ['state_id'=>14, 'city_name'=>'고성군'],
            ['state_id'=>14, 'city_name'=>'김해시'],
            ['state_id'=>14, 'city_name'=>'남해군'],
            ['state_id'=>14, 'city_name'=>'밀양시'],
            ['state_id'=>14, 'city_name'=>'사천시'],
            ['state_id'=>14, 'city_name'=>'산청군'],
            ['state_id'=>14, 'city_name'=>'양산시'],
            ['state_id'=>14, 'city_name'=>'의령군'],
            ['state_id'=>14, 'city_name'=>'진주시'],
            ['state_id'=>14, 'city_name'=>'창녕군'],
            ['state_id'=>14, 'city_name'=>'창원시'],
            ['state_id'=>14, 'city_name'=>'통영시'],
            ['state_id'=>14, 'city_name'=>'하동군'],
            ['state_id'=>14, 'city_name'=>'함안군'],
            ['state_id'=>14, 'city_name'=>'함양군'],
            ['state_id'=>14, 'city_name'=>'합천군'],
            //경상북도
            ['state_id'=>15, 'city_name'=>'경산시'],
            ['state_id'=>15, 'city_name'=>'경주시'],
            ['state_id'=>15, 'city_name'=>'고령군'],
            ['state_id'=>15, 'city_name'=>'구미시'],
            ['state_id'=>15, 'city_name'=>'군위군'],
            ['state_id'=>15, 'city_name'=>'김천시'],
            ['state_id'=>15, 'city_name'=>'문경시'],
            ['state_id'=>15, 'city_name'=>'봉화군'],
            ['state_id'=>15, 'city_name'=>'상주시'],
            ['state_id'=>15, 'city_name'=>'성주군'],
            ['state_id'=>15, 'city_name'=>'안동시'],
            ['state_id'=>15, 'city_name'=>'영덕군'],
            ['state_id'=>15, 'city_name'=>'영양군'],
            ['state_id'=>15, 'city_name'=>'영주시'],
            ['state_id'=>15, 'city_name'=>'영천시'],
            ['state_id'=>15, 'city_name'=>'예천군'],
            ['state_id'=>15, 'city_name'=>'울릉군'],
            ['state_id'=>15, 'city_name'=>'울진군'],
            ['state_id'=>15, 'city_name'=>'의성군'],
            ['state_id'=>15, 'city_name'=>'청도군'],
            ['state_id'=>15, 'city_name'=>'청송군'],
            ['state_id'=>15, 'city_name'=>'칠곡군'],
            ['state_id'=>15, 'city_name'=>'포항시'],
            //제주특별자치도
            ['state_id'=>16, 'city_name'=>'강화군'],
            ['state_id'=>16, 'city_name'=>'계양구'],
            ['state_id'=>16, 'city_name'=>'남구'],
            ['state_id'=>16, 'city_name'=>'남동구'],
            ['state_id'=>16, 'city_name'=>'동구'],
            ['state_id'=>16, 'city_name'=>'부평구'],
            ['state_id'=>16, 'city_name'=>'서구'],
            ['state_id'=>16, 'city_name'=>'연수구'],
            ['state_id'=>16, 'city_name'=>'옹진군'],
            ['state_id'=>16, 'city_name'=>'중구'],
            //세종특별자치시
            ['state_id'=>17, 'city_name'=>'세종특별자치시'],
        ]);
    }
}
